"""change pubyear to wordcount

Revision ID: 491626237bb1
Revises: 725d575ea784
Create Date: 2022-03-15 17:15:39.358331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491626237bb1'
down_revision = '725d575ea784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('wordcount', sa.Integer(), nullable=True))
    op.drop_column('books', 'pubyear')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pubyear', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('books', 'wordcount')
    # ### end Alembic commands ###
