"""add boolean for book files

Revision ID: 5871de077c3a
Revises: 
Create Date: 2022-03-07 16:52:47.831877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5871de077c3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('epub', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('kepub', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('mobi', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'mobi')
    op.drop_column('books', 'kepub')
    op.drop_column('books', 'epub')
    # ### end Alembic commands ###
