"""Add series name sort

Revision ID: 6fdb1c9e4912
Revises: c969c52dcb3e
Create Date: 2022-04-03 19:30:19.786575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdb1c9e4912'
down_revision = 'c969c52dcb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('name_sort', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'name_sort')
    # ### end Alembic commands ###
