"""remove boolean for book files

Revision ID: 8b67a7bd22b5
Revises: 5871de077c3a
Create Date: 2022-03-07 18:04:35.531905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b67a7bd22b5'
down_revision = '5871de077c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'mobi')
    op.drop_column('books', 'kepub')
    op.drop_column('books', 'epub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('epub', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('kepub', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('mobi', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
